### ISSUE TITLE
Mails not coming

### ISSUE THREAD

**Issue by wmdhosting** [doublesecretagency/craft-notifier#13]
Description
I have created a trigger and messages, but the send is not working. The application email is configured by SMTP.
On same install i use Formie and mails working ok..

Steps to reproduce

Сreated a trigger;
Configured for save all entries;
Сreated a message with template;
I don't receive emails.

Plugin version: 2.2.4
Craft version: Pro 3.7.43
Multi-site: Yes
PHP version: 7.4.29
Email Transport Type: SMTP
Database driver & version: MySQL 5.5.5

**Comment by lindseydiloreto** [comment]
Thanks for confirming that emails work under other conditions.

What are you seeing reported in the Notification Logs?

https://plugins.doublesecretagency.com/notifier/guides/logs/

**Comment by wmdhosting** [comment]
I Just now published new entry.. 
Here are just part of logs.. have about this more.. just for this 1 entry..  similar.. 
No mails came here..
![2022-06-01_20-13-31](https://user-images.githubusercontent.com/76176291/171474867-6fd117fc-daca-442c-8335-acab066410ed.png)
![Snag_1cf733bf](https://user-images.githubusercontent.com/76176291/171474879-6d006b02-6c9a-4807-a5a0-a9e48447d4e0.png)
.

**Comment by lindseydiloreto** [comment]
Interesting... I see a combination of email failures, successes, and suppressed duplicates.

---

**Failed (check email settings)**
 - 8:11:34 (x2)
 - 8:11:55 (x2)

**Successes**
 - 8:11:34
 - 8:11:54
 - 8:11:55

**Suppressed Duplicates**
 - Most of the lines after 8:11:55

---

It's tricky to see exactly what the problem is, since a lot of things seem to be happening when you save an entry.

If you don't mind, perhaps we should move this conversation to Discord DM. We can step through the issue together, it will be easier to troubleshoot if I can see the censored details.

**Comment by wmdhosting** [comment]
I cheked server logs and seems mails are sent..  
but for some reason on gmail of developer mails did not coming.. 
nor on my mail..    that is not gmail.  

now i changed my mail in some other and working OK::

**Comment by lindseydiloreto** [comment]
Ok great! Sounds like the emails were just getting caught in some sort of spam filter.

Thanks for reporting back! 👍
