### ISSUE TITLE
Subject field not parsing globals

### ISSUE THREAD

**Issue by dowadidi** [doublesecretagency/craft-notifier#17]
We tried to use a global variable to make the subject editable for the client. But it rendered empty.

Craft version: 4.3.6.1
Plugin version: 0.10.1

**Comment by lindseydiloreto** [comment]
Hi @dowadidi. I just tested this, and it seems that everything is working normally.

Since it requires the full scope of Twig, use **double curly braces** to specify the global set and field handle...

```twig
{{ myGlobalSet.myGlobalField }}
```

I just tried the example above, and it worked flawlessly.

<img width="450" alt="Example of using a Global field value as the message subject line." src="https://user-images.githubusercontent.com/5309692/213592984-3572a07c-ace6-43d6-9e25-531e8be1c1fa.png">

---

I'm going to close this thread because it seems like everything is working normally. Let me know if I missed something.
